/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER TAV_MDY3131_PFINAL_EA2_2 IDENTIFIED BY "MDY3131.practfinal2_ea2"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER TAV_MDY3131_PFINAL_EA2_2 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO TAV_MDY3131_PFINAL_EA2_2;
GRANT "RESOURCE" TO TAV_MDY3131_PFINAL_EA2_2;
ALTER USER TAV_MDY3131_PFINAL_EA2_2 DEFAULT ROLE "RESOURCE";

/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER TAV_MDY3131_PFINAL_EA2_2 IDENTIFIED BY "MDY3131.practfinal2_ea2"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER TAV_MDY3131_PFINAL_EA2_2 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO TAV_MDY3131_PFINAL_EA2_2;
GRANT "RESOURCE" TO TAV_MDY3131_PFINAL_EA2_2;
ALTER USER TAV_MDY3131_PFINAL_EA2_2 DEFAULT ROLE "RESOURCE";